name = "Dolo"
uuid = "9d24351c-2990-5e1b-a277-04c4b809c898"
version = "0.4.4"

[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
BasisMatrices = "08854c51-b66b-5062-a90d-8e7ae4547a49"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Dolang = "e5c7262c-e9d2-5620-ad8e-1af14eb8a8e3"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
Lerche = "d42ef402-04e6-4356-9f73-091573ea58dc"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuantEcon = "fcd29c91-0bd7-5a09-975d-7ac3f643a60c"
SimplePlots = "307c2aad-90be-4152-b348-f51955fac6ce"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StringDistances = "88034a9c-02f8-509d-84a9-84ec65e18404"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
julia = "^1.7"
AxisArrays = "^0.4.4"
BasisMatrices = "^0.7"
Compat = "^3.40.0"
DataStructures = "^0.18"
Distributions = "^0.25"
Dolang = "^3.3.0"
Formatting = "^0.4.2"
HTTP = "^0.9"
IterTools = "^1.3"
IterativeSolvers = "^0.9.2"
Lerche = "^0.5.2"
MacroTools = "^0.5.6"
NLsolve = "^4.5.1"
Optim = "^1.5.0"
QuantEcon = "^0.16.3"
StaticArrays = "^1.2.13"
StringDistances = "^0.11.1"
YAML = "^0.4.7"
